module.exports = {
  purge: {
    enabled: true,
    content: [
      './pages/**/*.js',
      './components/**/*.js',
      './node_modules/react-day-picker/**/*.css',
    ],
    options: {
      whitelist: [
        'flex-1',
        'sm:flex-row',
        'text-center',
        'sm:items-start',
        'sm:items-center',
        'font-medium',
        'font-extrabold',
        'text-3xl',
        'sm:text-4xl',
        'lg:text-xl',
        'leading-loose',
        'sm:py-16',
        'py-10',
        'py-2',
        'sm:px-10',
        'sm:py-0',
        'md:px-6',
        'lg:px-10',
        'p-6',
        'px-10',
        'pb-6',
        'sm:pb-3',
        'pb-16',
        'mx-4',
        'mx-8',
        'sm:my-12',
        'sm:mb-0',
        'mb-2',
        'mb-6',
        'mb-10',
        'mb-20',
        'mt-4',
        'mt-12',
        '-my-16',
        'border-b',
        'border-t',
        'w-56',
        'sm:border-b-0',
        'bg-primary-blue',
        'bg-gray-200',
        'bg-gray-800',
        'border-t-2',
        'sm:bg-transparent',
        'grid',
        'grid-cols-1',
        'sm:grid-cols-2',
        'max-w-screen-lg',
        'max-w-md',
        'shadow',
        'overflow-hidden',
        'tracking-wider',
        'font-black',
      ],
    },
  },
  theme: {
    extend: {
      colors: {
        'primary-blue': '#245688',
        'secondary-blue': '#0CB3FA',
      },
      opacity: {
        40: '.4',
        90: '.9',
      },
      fontSize: {
        '12xl': '10rem',
        '16xl': '14rem',
      },
      fontFamily: {
        body: ['Source Sans Pro'],
      },
      inset: {
        '1/4': '0.25rem',
        '1/2': '0.5rem',
        '3/4': '0.75rem',
      },
      height: {
        0.2: '0.05rem',
      },
      zIndex: {
        100: 100,
        200: 200,
      },
    },
  },
  variants: {
    borderColor: ['responsive', 'hover', 'focus', 'focus-within'],
  },
  future: {
    removeDeprecatedGapUtilities: true,
  },
};
