export const INITIAL_BOOKING = {
  resort: null,
  firstDay: null,
  lastDay: null,
  duration: null,
  adultsPrice: 0,
  childrenPrice: 0,
  totalPrice: 0,
  adults: [],
  children: [],
  deliveryAddress: null,
  isValid: false,
  isPaid: false,
  paymentIntentId: null,
};
