export const INITIAL_BOOKING = {
  resort: null,
  firstDay: null,
  lastDay: null,
  duration: 0,
  adultsPrice: 0,
  childrenPrice: 0,
  totalPrice: 0,
  adults: [],
  children: [],
  email: '',
  name: '',
  countryCode: 'FR',
  deliveryAddress: '',
  paymentIntentId: null,
  isRegisteredToNewsletter: true,
  isValid: false,
  isPaid: false,
};
