export const INITIAL_BOOKING = {
  resort: null,
  firstDay: null,
  lastDay: null,
  duration: null,
  adultsPrice: 0,
  childrenPrice: 0,
  totalPrice: 0,
  adults: [],
  children: [],
  email: null,
  name: null,
  countryCode: 'FR',
  deliveryAddress: null,
  paymentIntentId: null,
  isRegisteredToNewsletter: true,
  isValid: false,
  isPaid: false,
};
